model: "base_group2"
model_directory: "models/"
batch_size: 96
max_sequence_length: 128

in_path: "data/annotation_data_0522.txt"
out_path: "output/test.parquet"
feedback: rating # or ratings of validation / test
