defaults:
  - _self_
  - model: baidu
  - tokens: baidu
  - override hydra/hydra_logging: disabled # Disable hydra logging
  - override hydra/job_logging: disabled # Disable hydra logging

batch_size: 96
max_sequence_length: 128
half_precision: True # Encode features using fp16

data_type: train # [train, val]
data_directory: "data/"
out_directory: "output/"

# Parse train files in chunks, the test set is processed in a single part:
train_part: 0 # Baidu dataset part: 0 - 1999
train_split_id: 0 # One dataset part typically has 10 splits, each with 65_536 queries
train_queries_per_split: 65_536

ignored_titles:
  - MISSING
  - WHAT_OTHER_PEOPLE_SEARCHED

hydra:
  output_subdir: null  # Disable hydra logging
  run:
    dir: .
