defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    mem_gb: 32
    cpus_per_task: 8
    array_parallelism: 1
    partition: gpu
    gres: gpu:1

model: "base_group2"
model_directory: "models/"
batch_size: 96
max_sequence_length: 128

in_directory: "data/"
in_file: "annotation_data_0522.txt"
in_type: test # [train, test]

out_directory: "output/"
half_precision: True # Encode features using fp16
